### PR TITLE
AIRO-1604 Adding HDRP support

### PR DESCRIPTION
**Pull request by mrpropellers**
## Proposed change(s)

While we've had some HDRP versions of some of the Robotics-Warehouse assets floating around, we had no centralized repository for them, nor were they fully validated to work with this package.

This change splits the Robotics-Warehouse package into three packages: base, urp, and hdrp. Both urp and hdrp depend on the base package, but when one includes the Robotics-Warehouse package in a project they will now need to include both base and whichever version they're using. 

Import scaling issues are fixed in the HDRP version, but not in the URP version, and there are still some outstanding issues documented in Jira.

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)
https://jira.unity3d.com/browse/AIRO-1604
https://jira.unity3d.com/browse/AIRO-1602
https://jira.unity3d.com/browse/AIRO-1605
https://jira.unity3d.com/browse/AIRO-1606
https://jira.unity3d.com/browse/AIRO-1607

### Types of change(s)
- [x] Bug fix
- [x] New feature
- [x] Code refactor
- [ ] Documentation update

## Testing and Verification

Ran warehouse generation by interacting with the buttons in Inspector for both URP and HDRP versions. It works nominally, but there are a bunch of issues unrelated to this change that have been logged as Tech Debt.

### Test Configuration:
- Unity Version: 2021.1.11f
- Unity machine OS + version: Windows 10

## Checklist
- [x] Ensured this PR is up-to-date with the target branch
- [ ] Updated the [Changelog](../CHANGELOG.md) and described changes in the [Unreleased section](../CHANGELOG.md#unreleased)
- [ ] Updated the documentation as appropriate (**Note**: Work here is incomplete and there is a [follow-up task](https://jira.unity3d.com/browse/AIRO-1607) to update documentation)

### CODE REVIEW

**Review by peifeng-unity — APPROVED** [review]
I checked the HDRP and UPR projects on my local and both of them look good in the Editor.

**Comment by at669** [comment]
in the WarehouseProjectHDRP, the `Generate All On Start` only generates the shell and not the shelves--is that intentional?

**Comment by mrpropellers** [comment]
> RP, the `Generate All On Start` only generates the shell and not the shelves--is that intentional?

**Comment by mrpropellers** [comment]
> in the WarehouseProjectHDRP, the `Generate All On Start` only generates the shell and not the shelves--is that intentional?

It is not - are the shelves missing from the hierarchy too? I've found they fail to show up in a variety of different ways.  They might not be there at all, or they might be there but they are 100x too big so they're outside the warehouse, or they might be there and the correct scale but the meshes are missing...

**Review by at669 — APPROVED** [review]

**Pull request closed without merging**
